# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm
      - goarch: 386
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - homepage: 'https://github.com/0x20F/homebrew-carbon'
    description: 'Build tool for custom configuration of multiple smaller services, and wrapper commands for docker containers to make your life easier.'
    folder: Formula
    commit_author:
      name: '0x20F'
      email: '0x20fa@gmail.com'
    tap:
      owner: '0x20F'
      name: 'homebrew-carbon'

nfpms:
  - id: 'co2'
    package_name: 'carbon'
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64
    homepage: https://github.com/0x20F/carbon
    maintainer: 0x20F <0x20fa@gmail.com>
    description: Build tool for custom configuration of multiple smaller services, and wrapper commands for docker containers to make your life easier.
    license: MPL-2.0
    formats:
      - apk
      - deb
      - rpm
