on:
  push:
    branches: [ '**' ]

jobs:
  test-code:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2

      - run: go get .

      - name: Run tests
        run: go test -v ./...